//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbe.test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dbe.test.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] docgentest_letter {
            get {
                object obj = ResourceManager.GetObject("docgentest_letter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;root xmlns=&quot;LetterTest&quot;&gt;
        ///  &lt;to&gt;Jack Smith&lt;/to&gt;
        ///  &lt;from&gt;Matt Scott&lt;/from&gt;
        ///  &lt;place&gt;
        ///    &lt;at&gt;Yankees Stadium&lt;/at&gt;
        ///    &lt;date&gt;2/2/2010&lt;/date&gt;
        ///  &lt;/place&gt;
        ///&lt;/root&gt;.
        /// </summary>
        internal static string docgentest_letterdata1 {
            get {
                return ResourceManager.GetString("docgentest_letterdata1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;root xmlns=&quot;LetterTest&quot;&gt;
        ///  &lt;to&gt;Bob Smith&lt;/to&gt;
        ///  &lt;from&gt;Jack Doe&lt;/from&gt;
        ///  &lt;place&gt;
        ///    &lt;at&gt;1 Microsoft Way, Redmond, WA&lt;/at&gt;
        ///    &lt;date&gt;10/2/2010&lt;/date&gt;
        ///  &lt;/place&gt;
        ///&lt;/root&gt;.
        /// </summary>
        internal static string docgentest_letterdata2 {
            get {
                return ResourceManager.GetString("docgentest_letterdata2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;noNs&gt;
        /// &lt;foo/&gt;
        ///&lt;/noNs&gt;.
        /// </summary>
        internal static string instance1_xml {
            get {
                return ResourceManager.GetString("instance1_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema id=&quot;Picnic&quot; targetNamespace=&quot;http://tempuri.org/Picnic.xsd&quot; elementFormDefault=&quot;qualified&quot; xmlns=&quot;http://tempuri.org/Picnic.xsd&quot; xmlns:mstns=&quot;http://tempuri.org/Picnic.xsd&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///&lt;xs:element name=&quot;PicNic&quot; type=&quot;PicnicType&quot;&gt;
        ///&lt;/xs:element&gt;
        ///&lt;xs:complexType name=&quot;PicnicType&quot;&gt;
        ///&lt;xs:sequence&gt;
        ///&lt;xs:element name=&quot;who&quot; type=&quot;xs:string&quot;&gt;Sam&lt;/xs:element&gt;
        ///&lt;xs:element name=&quot;location&quot; type=&quot;xs:string&quot;&gt;Reedville&lt;/xs:element&gt;
        ///&lt;xs [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string schema1_xsd {
            get {
                return ResourceManager.GetString("schema1_xsd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xsd:schema xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///
        ///  &lt;xsd:element name=&quot;SONG&quot; type=&quot;songType&quot;/&gt;
        /// 
        ///  &lt;xsd:complexType name=&quot;songType&quot;&gt;
        ///    &lt;xsd:sequence&gt;
        ///      &lt;xsd:element name=&quot;TITLE&quot;     type=&quot;xsd:string&quot;
        ///        minOccurs=&quot;1&quot; maxOccurs=&quot;1&quot;/&gt;
        ///      &lt;xsd:element name=&quot;COMPOSER&quot;  type=&quot;xsd:string&quot; 
        ///        minOccurs=&quot;1&quot; maxOccurs=&quot;unbounded&quot;/&gt;
        ///      &lt;xsd:element name=&quot;PRODUCER&quot;  type=&quot;xsd:string&quot; 
        ///        minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;/&gt;
        ///      &lt;xsd:element name=&quot;PUBLISHER&quot; type=&quot;xsd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string schema2_xsd {
            get {
                return ResourceManager.GetString("schema2_xsd", resourceCulture);
            }
        }
        
        internal static byte[] test_docx {
            get {
                object obj = ResourceManager.GetObject("test_docx", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
