// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using System.Xml;
namespace dbe.test
{
    /// <summary>
    ///This is a test class for dbe.XmlUtil and is intended
    ///to contain all dbe.XmlUtil Unit Tests
    ///</summary>
    [TestClass()]
    public class XmlUtilTest
    {


        private TestContext testContextInstance;

        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }
        #region Additional test attributes
        // 
        //You can use the following additional attributes as you write your tests:
        //
        //Use ClassInitialize to run code before running the first test in the class
        //
        //[ClassInitialize()]
        //public static void MyClassInitialize(TestContext testContext)
        //{
        //}
        //
        //Use ClassCleanup to run code after all tests in a class have run
        //
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Use TestInitialize to run code before running each test
        //
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{
        //}
        //
        //Use TestCleanup to run code after each test has run
        //
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //
        #endregion

        /// <summary>
        ///A test for GetNsFromStr (string)
        ///</summary>
        [DeploymentItem("dbe.exe")]
        [TestMethod()]
        public void GetNsFromStrTest()
        {
            string sXml = "<z:foo xmlns:f='anotherNs' xmlns='globalNs' xmlns:z='targetNs'/>";

            string expected = "targetNs";
            string actual;

            actual = dbe.test.dbe_XmlUtilAccessor.GetNsFromStr(sXml);

            Assert.AreEqual(expected, actual, "dbe.XmlUtil.GetNsFromStr did not return the expected value.");
        }


        /// <summary>
        ///A test for FSchema (string)
        ///</summary>
        [DeploymentItem("dbe.exe")]
        [TestMethod()]
        public void FSchemaTest()
        {
            bool result;
            result = dbe.test.dbe_XmlUtilAccessor.FSchema(Resource1.instance1_xml);
            Assert.IsFalse(result, "dbe.XmlUtil.FSchema did not return the expected value.");
            result = dbe.test.dbe_XmlUtilAccessor.FSchema(Resource1.schema1_xsd);
            Assert.IsTrue(result, "dbe.XmlUtil.FSchema did not return the expected value.");
            result = dbe.test.dbe_XmlUtilAccessor.FSchema(Resource1.schema2_xsd);
            Assert.IsTrue(result, "dbe.XmlUtil.FSchema did not return the expected value.");
        }
    }


}
