//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbe.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dbe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap banner {
            get {
                object obj = ResourceManager.GetObject("banner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap blank16x16 {
            get {
                object obj = ResourceManager.GetObject("blank16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CheckGrammarHS {
            get {
                object obj = ResourceManager.GetObject("CheckGrammarHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a newer version available. Uninstall this version from the control panel add/remove programs and install the new version from the link below..
        /// </summary>
        internal static string CheckUpdatesNewAvail {
            get {
                return ResourceManager.GetString("CheckUpdatesNewAvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently checking to see if a newer version is available....
        /// </summary>
        internal static string CheckUpdatesProgress {
            get {
                return ResourceManager.GetString("CheckUpdatesProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates are currently available..
        /// </summary>
        internal static string CheckUpdatesUpToDate {
            get {
                return ResourceManager.GetString("CheckUpdatesUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.codeplex.com/dbe/.
        /// </summary>
        internal static string CodePlexDbeUrl {
            get {
                return ResourceManager.GetString("CodePlexDbeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.codeplex.com/dbe/Release/ProjectReleases.aspx.
        /// </summary>
        internal static string CodePlexReleaseUrl {
            get {
                return ResourceManager.GetString("CodePlexReleaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the Custom XML part?.
        /// </summary>
        internal static string ConfirmDeletePart {
            get {
                return ResourceManager.GetString("ConfirmDeletePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to revert changes made to this XML document?.
        /// </summary>
        internal static string ConfirmRevertXml {
            get {
                return ResourceManager.GetString("ConfirmRevertXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (C) 2010 Microsoft Corporation.
        /// </summary>
        internal static string CopyRight1 {
            get {
                return ResourceManager.GetString("CopyRight1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved..
        /// </summary>
        internal static string CopyRight2 {
            get {
                return ResourceManager.GetString("CopyRight2", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap DataContainer_NewRecordHS {
            get {
                object obj = ResourceManager.GetObject("DataContainer_NewRecordHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dbe {
            get {
                object obj = ResourceManager.GetObject("dbe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Content Control Toolkit.
        /// </summary>
        internal static string DbeName {
            get {
                return ResourceManager.GetString("DbeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fix XML error before leaving this Custom XML part: .
        /// </summary>
        internal static string FixXmlErrorRequestBeforeLeave {
            get {
                return ResourceManager.GetString("FixXmlErrorRequestBeforeLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fix XML error in the current document before creating a new part: .
        /// </summary>
        internal static string FixXmlErrorRequestBeforeNewPart {
            get {
                return ResourceManager.GetString("FixXmlErrorRequestBeforeNewPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fix XML error before switching views:.
        /// </summary>
        internal static string FixXmlErrorRequestBeforeSwitchViews {
            get {
                return ResourceManager.GetString("FixXmlErrorRequestBeforeSwitchViews", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap gradient {
            get {
                object obj = ResourceManager.GetObject("gradient", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HtmlBalanceBracesHS {
            get {
                object obj = ResourceManager.GetObject("HtmlBalanceBracesHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only leaf elements and attributes can be dragged and mapped to content controls..
        /// </summary>
        internal static string IllegalXmlTreeDrag {
            get {
                return ResourceManager.GetString("IllegalXmlTreeDrag", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap infoicon_better {
            get {
                object obj = ResourceManager.GetObject("infoicon_better", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap infoicon_bg {
            get {
                object obj = ResourceManager.GetObject("infoicon_bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Limited Permissive License (Ms-LPL)
        ///
        ///This license governs use of the accompanying software. If you use the software, you accept this license. If you do not accept the license, do not use the software.
        ///
        ///1. Definitions
        ///The terms ¡°reproduce,¡± ¡°reproduction,¡± ¡°derivative works,¡± and ¡°distribution¡± have the same meaning here as under U.S. copyright law.
        ///A ¡°contribution¡± is the original software, or any additions or changes to the software.
        ///A ¡°contributor¡± is any person that distribut [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string license_mslpl {
            get {
                return ResourceManager.GetString("license_mslpl", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap minus {
            get {
                object obj = ResourceManager.GetObject("minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No Namespace).
        /// </summary>
        internal static string NoNamespaceDisplayName {
            get {
                return ResourceManager.GetString("NoNamespaceDisplayName", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap open {
            get {
                object obj = ResourceManager.GetObject("open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PageUpHS {
            get {
                object obj = ResourceManager.GetObject("PageUpHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap plus {
            get {
                object obj = ResourceManager.GetObject("plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reformat {
            get {
                object obj = ResourceManager.GetObject("reformat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap revert {
            get {
                object obj = ResourceManager.GetObject("revert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string StatusBarReady {
            get {
                return ResourceManager.GetString("StatusBarReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error: .
        /// </summary>
        internal static string SyntaxCheckErrorPrefix {
            get {
                return ResourceManager.GetString("SyntaxCheckErrorPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot validate syntax because XML document is empty..
        /// </summary>
        internal static string SyntaxCheckFailureEmptyXml {
            get {
                return ResourceManager.GetString("SyntaxCheckFailureEmptyXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No syntax errors found..
        /// </summary>
        internal static string SyntaxCheckSuccess {
            get {
                return ResourceManager.GetString("SyntaxCheckSuccess", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap VSProject_generatedfile {
            get {
                object obj = ResourceManager.GetObject("VSProject_generatedfile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VSProject_genericfile {
            get {
                object obj = ResourceManager.GetObject("VSProject_genericfile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wordlocator {
            get {
                object obj = ResourceManager.GetObject("wordlocator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
